name: Documentation Quality

on:
  push:
    branches: [main]
    paths:
      - '**.md'
      - 'docs/**'
  pull_request:
    branches: [main]
    paths:
      - '**.md'
      - 'docs/**'

jobs:
  markdown-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Markdown Lint
        uses: DavidAnson/markdownlint-cli2-action@v11
        with:
          globs: '**/*.md'

  link-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Install linkinator
        run: npm install -g linkinator

      - name: Check markdown links
        run: linkinator '**/*.md' --skip 'https://api.github.com' --markdown

  mermaid-validation:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Find Mermaid Code Blocks
        id: find-mermaid
        run: |
          MERMAID_FILES=$(grep -l '```mermaid' --include="*.md" -r .)
          echo "Found Mermaid diagrams in: $MERMAID_FILES"
          echo "mermaid_files=$MERMAID_FILES" >> $GITHUB_OUTPUT

      - name: Setup Node.js
        if: steps.find-mermaid.outputs.mermaid_files != ''
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Install Mermaid CLI
        if: steps.find-mermaid.outputs.mermaid_files != ''
        run: npm install -g @mermaid-js/mermaid-cli

      - name: Validate Mermaid Syntax
        if: steps.find-mermaid.outputs.mermaid_files != ''
        run: |
          for file in ${{ steps.find-mermaid.outputs.mermaid_files }}; do
            echo "Validating Mermaid syntax in $file"
            npx mmdc --input "$file" --outputFormat svg --output /tmp/output.svg
          done
